"""init

Revision ID: 6c32a11d992c
Revises: 
Create Date: 2022-03-10 21:54:16.286228

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "6c32a11d992c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authors",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("bio", sqlmodel.sql.sqltypes.AutoString(length=7000), nullable=False),
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_authors_id"), "authors", ["id"], unique=False)
    op.create_index(op.f("ix_authors_name"), "authors", ["name"], unique=False)
    op.create_table(
        "books",
        sa.Column("genres", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("dimensions", sa.ARRAY(sa.Float()), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "summary", sqlmodel.sql.sqltypes.AutoString(length=5000), nullable=False
        ),
        sa.Column("hard_cover_price", sa.Numeric(scale=2), nullable=True),
        sa.Column("paperback_price", sa.Numeric(scale=2), nullable=True),
        sa.Column("published_year", sa.Integer(), nullable=False),
        sa.Column("num_of_pages", sa.Integer(), nullable=False),
        sa.Column("reading_age", sa.Integer(), nullable=True),
        sa.Column(
            "isbn_10", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column("item_weight_pounds", sa.Float(), nullable=False),
        sa.Column("stock_qty", sa.Integer(), nullable=False),
        sa.Column("is_bestseller", sa.Boolean(), nullable=True),
        sa.Column("num_of_reviews", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Numeric(scale=2), nullable=True),
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_books_id"), "books", ["id"], unique=False)
    op.create_index(op.f("ix_books_title"), "books", ["title"], unique=False)
    op.create_table(
        "genres",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_genres_id"), "genres", ["id"], unique=False)
    op.create_index(op.f("ix_genres_name"), "genres", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_genres_name"), table_name="genres")
    op.drop_index(op.f("ix_genres_id"), table_name="genres")
    op.drop_table("genres")
    op.drop_index(op.f("ix_books_title"), table_name="books")
    op.drop_index(op.f("ix_books_id"), table_name="books")
    op.drop_table("books")
    op.drop_index(op.f("ix_authors_name"), table_name="authors")
    op.drop_index(op.f("ix_authors_id"), table_name="authors")
    op.drop_table("authors")
    # ### end Alembic commands ###
