"""init

Revision ID: acef089c5478
Revises: 
Create Date: 2022-03-09 19:57:06.951090

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "acef089c5478"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "books",
        sa.Column(
            "language", sa.Enum("spanish", "english", name="language"), nullable=False
        ),
        sa.Column("genres", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("dimensions", sa.ARRAY(sa.Float()), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "summary", sqlmodel.sql.sqltypes.AutoString(length=5000), nullable=False
        ),
        sa.Column("hard_cover_price", sa.Numeric(scale=2), nullable=True),
        sa.Column("paperback_price", sa.Numeric(scale=2), nullable=True),
        sa.Column("published_year", sa.Integer(), nullable=False),
        sa.Column("num_of_pages", sa.Integer(), nullable=False),
        sa.Column("reading_age", sa.Integer(), nullable=True),
        sa.Column(
            "isbn_10", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column("item_weight_pounds", sa.Float(), nullable=False),
        sa.Column("stock_qty", sa.Integer(), nullable=False),
        sa.Column("is_bestseller", sa.Boolean(), nullable=True),
        sa.Column("num_of_reviews", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Numeric(scale=2), nullable=True),
        sa.Column("id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_books_title"), "books", ["title"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_books_title"), table_name="books")
    op.drop_table("books")
    # ### end Alembic commands ###
