"""add book-author rel

Revision ID: ba4fa4e54cec
Revises: fd5161000196
Create Date: 2022-03-13 21:52:15.415712

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ba4fa4e54cec"
down_revision = "fd5161000196"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("authors", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("books", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column(
        "books", sa.Column("author_id", postgresql.UUID(as_uuid=True), nullable=True)
    )
    op.create_foreign_key(None, "books", "authors", ["author_id"], ["id"])
    op.add_column("genres", sa.Column("created_at", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("genres", "created_at")
    op.drop_constraint(None, "books", type_="foreignkey")
    op.drop_column("books", "author_id")
    op.drop_column("books", "created_at")
    op.drop_column("authors", "created_at")
    # ### end Alembic commands ###
