"""books tables extra cols

Revision ID: fd5161000196
Revises: ef4ff4f8443f
Create Date: 2022-03-13 19:53:01.513593

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fd5161000196"
down_revision = "ef4ff4f8443f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "books",
        sa.Column(
            "language", sa.Enum("english", "spanish", name="language"), nullable=True
        ),
    )
    op.add_column("books", sa.Column("published_year", sa.Integer(), nullable=False))
    op.add_column("books", sa.Column("num_of_pages", sa.Integer(), nullable=False))
    op.add_column("books", sa.Column("reading_age", sa.Integer(), nullable=True))
    op.add_column("books", sa.Column("item_weight_pounds", sa.Float(), nullable=False))
    op.add_column("books", sa.Column("stock_qty", sa.Integer(), nullable=False))
    op.add_column("books", sa.Column("is_bestseller", sa.Boolean(), nullable=True))
    op.add_column(
        "books", sa.Column("dimensions", sa.ARRAY(sa.Float()), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("books", "dimensions")
    op.drop_column("books", "is_bestseller")
    op.drop_column("books", "stock_qty")
    op.drop_column("books", "item_weight_pounds")
    op.drop_column("books", "reading_age")
    op.drop_column("books", "num_of_pages")
    op.drop_column("books", "published_year")
    op.drop_column("books", "language")
    # ### end Alembic commands ###
