# Generated by Django 4.0.3 on 2022-03-16 20:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0004_delete_genre_alter_book_genres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('bio', models.CharField(max_length=7000)),
                ('books', models.ManyToManyField(to='books.book')),
            ],
        ),
    ]
