# Generated by Django 4.0.3 on 2022-03-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_authors_alter_book_genres_alter_book_summary'),
        ('authors', '0002_author_created_at_author_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(blank=True, to='books.book'),
        ),
    ]
