# Generated by Django 4.0.3 on 2022-03-16 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=7000)),
                ('hardcover_price', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('paperback_price', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
        ),
    ]
