# Generated by Django 4.0.3 on 2022-03-18 04:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('summary', models.TextField()),
                ('hardcover_price', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('paperback_price', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('published_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900, message='Min allowed year 1900'), django.core.validators.MaxValueValidator(2022, message='Max allowed year 2022')])),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('num_of_pages', models.PositiveIntegerField()),
                ('reading_age', models.PositiveIntegerField(blank=True, null=True)),
                ('item_weight', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Please add a valid weight value')])),
                ('stock_qty', models.PositiveIntegerField(default=1)),
                ('is_bestseller', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authors', models.ManyToManyField(blank=True, related_name='book_list', to='authors.author')),
                ('genres', models.ManyToManyField(blank=True, to='genres.genre')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(blank=True, null=True, upload_to='books/')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='books.book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.language'),
        ),
    ]
