# Generated by Django 4.0.3 on 2022-03-20 04:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_image_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-published_year', 'title']},
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.FloatField(blank=True, default=4.5, null=True, validators=[django.core.validators.MinValueValidator(0, message="rating can't be lower than 0"), django.core.validators.MaxValueValidator(5.0, message="rating can't be higher that 5.0")]),
        ),
        migrations.AlterField(
            model_name='book',
            name='hardcover_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='paperback_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
