# Generated by Django 4.0.3 on 2022-03-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
        ('books', '0003_alter_genre_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(related_name='books', to='genres.genre'),
        ),
    ]
