# Generated by Django 4.0.3 on 2022-03-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
        ('authors', '0001_initial'),
        ('books', '0004_delete_genre_alter_book_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='authors.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(to='genres.genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.CharField(max_length=2000),
        ),
    ]
