# Generated by Django 4.0.3 on 2022-03-16 23:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
        ('authors', '0003_alter_author_books'),
        ('books', '0005_book_authors_alter_book_genres_alter_book_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title', 'author']},
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default=None, max_length=13, unique=True, verbose_name='ISBN'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, to='authors.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(blank=True, to='genres.genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='item_weight',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Please add a valid weight value')]),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.language'),
        ),
    ]
