# Generated by Django 4.0.3 on 2022-03-17 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_language_alter_book_options_book_isbn_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(max_length=2000),
        ),
    ]
